version: '3.7'

services:
  database:
    image: postgres
    container_name: ordo_realitas_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ordo_realitas_api
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
